export const CoreKeys = {
  RESULT: {
    SUCCESS_WITH_ERROR: 'RESULT_SUCCESS_WITH_ERROR',
    FAIL_WITHOUT_ERROR: 'RESULT_FAIL_WITHOUT_ERROR',
    VALUE_ON_ERROR: 'RESULT_VALUE_ON_ERROR'
  },
  GUARD: {
    NULL_OR_UNDEFINED: 'GUARD_NULL_OR_UNDEFINED',
    EMPTY_STRING: 'GUARD_EMPTY_STRING'
  },
  VALIDATION: {
    INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL'
  },
  APP_ERROR: {
    UNEXPECTED: 'APP_ERROR_UNEXPECTED'
  },
  ERRORS: {
    VALIDATION: 'ERROR_VALIDATION',
    UNAUTHORIZED: 'ERROR_UNAUTHORIZED', // Kimliksiz (401)
    FORBIDDEN: 'ERROR_FORBIDDEN',       // Yetkisiz (403)
    NOT_FOUND: 'ERROR_NOT_FOUND',       // Bulunamadı (404)
    CONFLICT: 'ERROR_CONFLICT',         // Çakışma (409)
    SERVICE_UNAVAILABLE: 'ERROR_SERVICE_UNAVAILABLE', // Servis Yok (503)
    NOT_IMPLEMENTED: 'ERROR_NOT_IMPLEMENTED', // Yapılmadı (501)
    UNEXPECTED: 'ERROR_UNEXPECTED'
  },
  INFRA: {
    NETWORK_ERROR: 'INFRA_NETWORK_ERROR',
    TIMEOUT_ERROR: 'INFRA_TIMEOUT_ERROR',
    ENCRYPTION_FAILED: 'INFRA_ENCRYPTION_FAILED',
    DECRYPTION_FAILED: 'INFRA_DECRYPTION_FAILED',
    HASHING_FAILED: 'INFRA_HASHING_FAILED',
    INVALID_CIPHER_FORMAT: 'INFRA_INVALID_CIPHER_FORMAT'
  }
} as const;